services:
  backend:
    build: ./backend
    container_name: flight_dashboard_backend
    restart: unless-stopped
    networks:
      - media_network

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-/api}
        - NEXT_PUBLIC_APP_TITLE=${NEXT_PUBLIC_APP_TITLE:-}
    container_name: flight_dashboard_frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-/api}
      - NEXT_PUBLIC_APP_TITLE=${NEXT_PUBLIC_APP_TITLE:-}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
